// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_locations.Data;

#nullable disable

namespace mvc_locations.Migrations
{
    [DbContext(typeof(LocationContext))]
    [Migration("20220330164552_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("mvc_locations.Models.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("city_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("country_id")
                        .HasColumnType("int");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("id");

                    b.HasIndex("country_id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            city_name = "Zagreb",
                            country_id = 2,
                            latitude = 45.8150m,
                            longitude = 15.9819m
                        },
                        new
                        {
                            id = 2,
                            city_name = "Split",
                            country_id = 2,
                            latitude = 43.5147m,
                            longitude = 16.4435m
                        },
                        new
                        {
                            id = 3,
                            city_name = "Peking",
                            country_id = 1,
                            latitude = 39.9042m,
                            longitude = 116.4074m
                        },
                        new
                        {
                            id = 4,
                            city_name = "Šangaj",
                            country_id = 1,
                            latitude = 31.2304m,
                            longitude = 121.4737m
                        },
                        new
                        {
                            id = 5,
                            city_name = "Kampala",
                            country_id = 3,
                            latitude = 0.3476m,
                            longitude = 32.5825m
                        },
                        new
                        {
                            id = 6,
                            city_name = "Gulu",
                            country_id = 3,
                            latitude = 2.7724m,
                            longitude = 32.2881m
                        });
                });

            modelBuilder.Entity("mvc_locations.Models.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("country_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("country_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_name_eng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            id = 1,
                            country_code = "CHN",
                            country_name = "Kina",
                            country_name_eng = "China"
                        },
                        new
                        {
                            id = 2,
                            country_code = "HRV",
                            country_name = "Hrvatska",
                            country_name_eng = "Croatia"
                        },
                        new
                        {
                            id = 3,
                            country_code = "UGA",
                            country_name = "Uganda",
                            country_name_eng = "Uganda"
                        });
                });

            modelBuilder.Entity("mvc_locations.Models.City", b =>
                {
                    b.HasOne("mvc_locations.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("country_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
